import { z } from "zod";

const DateTypeLiterals = z.enum(["Date", "string", "number"]);
const BigIntTypeLiterals = z.enum(["bigint", "string", "number"]);

const StringBoolean = z
	.string()
	.transform(val => val === "true")
	.or(z.boolean());

export const ConfigSchema = z.object({
	enumPrefix: z.string().default(""),
	enumSuffix: z.string().default(""),
	modelPrefix: z.string().default(""),
	modelSuffix: z.string().default(""),
	typePrefix: z.string().default(""),
	typeSuffix: z.string().default(""),
	namespace: z.string().optional(),
	namespaceType: z.string().default("PrismaJson"),
	useType: z.string().optional(),
	headerComment: z.string().default("This file was auto-generated by prisma-generator-typescript-schema"),
	modelType: z.enum(["interface", "type"]).default("interface"),
	enumType: z.enum(["stringUnion", "enum", "object"]).default("stringUnion"),
	dateType: z
		.string()
		.refine(val => {
			const parts = val.split(" | ");
			if (parts.length > 2) return false;
			return parts.every(part => DateTypeLiterals.safeParse(part).success);
		})
		.default("Date"),
	bigIntType: z
		.string()
		.refine(val => {
			const parts = val.split(" | ");
			if (parts.length > 2) return false;
			return parts.every(part => BigIntTypeLiterals.safeParse(part).success);
		})
		.default("bigint"),
	decimalType: z.enum(["Decimal", "string", "number"]).default("Decimal"),
	bytesType: z.enum(["Buffer", "BufferObject", "string", "number[]"]).default("Buffer"),
	prefixCode: z.string().optional(),
	suffixCode: z.string().optional(),
	zodOutput: z.string().optional(),
	optionalRelations: StringBoolean.default(true),
	omitRelations: StringBoolean.default(false),
	optionalNullables: StringBoolean.default(false),
	prettier: StringBoolean.default(false)
});
